name: vrachipro
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/delete.png
    - assets/images/middle.png
    - assets/images/small.png
    - assets/images/sort-alt.png
    - assets/images/search.png
    - assets/images/record.png
    - assets/images/profile.png
    - assets/images/main.png
    - assets/images/cross-circle.png
    - assets/images/addfile.png
    - assets/images/edit.png
    - assets/images/arrow.png
    - assets/images/chat.png
    - assets/images/del.png
    - assets/images/uved.png
    - assets/images/kons.png
    - assets/images/musor.png
    - assets/images/mvr.png
    - assets/images/img.png
    - assets/images/default.png
    - assets/images/big.png
    - assets/images/circleotpr.png