name: vrachipro
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/delete.png
    - assets/images/middle.png
    - assets/images/small.png
    - assets/images/sort-alt.png
    - assets/images/search.png
    - assets/images/record.png
    - assets/images/profile.png
    - assets/images/main.png